name: staple_food_fortification
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^4.0.6
  hive:
  hive_flutter:
  cupertino_icons: ^1.0.5
  flutter_screenutil: any
  carousel_slider: ^4.2.1
  flutter_svg: ^1.1.6
  flutter_smart_dialog: ^4.7.3
  flutter_switch: ^0.3.2
  internet_connection_checker: ^1.0.0+1
  custom_sliding_segmented_control: ^1.7.3
  flutter_web_browser: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_html: ^3.0.0-alpha.6


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/


  fonts:
    - family: futura
      fonts:
        - asset: assets/fonts/futura_book_font.ttf